# Generated by Django 3.0.1 on 2020-10-05 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'managed': True},
        ),
    ]
